"""Наполнение базы при первом запуске (идемпотентно).

Два источника:
  • REAL  — реальные российские поставщики, найденные веб-поиском. У них указан
            реальный сайт-источник. Часть данных (цена, мин. заказ, сертификаты)
            у B2B-поставщиков закрыта и даётся «по запросу» — мы это НЕ выдумываем,
            а честно оставляем пустым (None) и показываем «нет данных».
  • DEMO  — синтетические, но реалистичные карточки с заполненными числовыми
            полями — чтобы наглядно показать работу сравнения и скоринга.
"""
from .database import SessionLocal
from .models import Supplier

# --- РЕАЛЬНЫЕ поставщики (источник — сайт компании, найдено веб-поиском) ---
REAL = [
    dict(
        name="ГК «Союзоптторг»",
        category="Ингредиенты",
        city="Москва",
        regions="Москва, вся Россия",
        description="Один из крупнейших дистрибьюторов пищевых ингредиентов и "
        "комплексных добавок для всех отраслей пищевой промышленности.",
        website="https://soyuzopttorg.com/",
        phone="+7 (499) 712-00-79",
        email=None,
        source="https://soyuzopttorg.com/",
        min_order="По запросу",
        price="По запросу",
        certificates="Документы и сертификаты — по запросу",
        has_certificates=None,
        delivery="Доставка по Москве и в регионы РФ",
        has_delivery=True,
        is_real=True,
    ),
    dict(
        name="НЕОС ИНГРЕДИЕНТС",
        category="Ингредиенты",
        city="Москва",
        regions="Москва и область, РФ",
        description="Поставщик ингредиентов для пищевой промышленности с 1990-х, "
        "имеет собственное производство в Московской области.",
        website="https://neos-ingredients.ru/",
        phone=None,
        email=None,
        source="https://neos-ingredients.ru/",
        min_order="По запросу",
        price="По запросу",
        certificates="Собственное производство, документы по запросу",
        has_certificates=None,
        delivery="Поставки по РФ",
        has_delivery=True,
        is_real=True,
    ),
    dict(
        name="RUSFLEX",
        category="Упаковка",
        city="Москва",
        regions="РФ",
        description="Производство гибкой полимерной упаковки (плёнка, рулонная "
        "упаковка, готовые пакеты) с печатью и без, оптом от производителя.",
        website="https://rusflex.com/",
        phone=None,
        email=None,
        source="https://rusflex.com/",
        min_order="Тиражи от производителя (по запросу)",
        price="По запросу",
        certificates="Пищевой допуск материалов — по запросу",
        has_certificates=None,
        delivery="Отгрузка по РФ",
        has_delivery=True,
        is_real=True,
    ),
    dict(
        name="Эдельвейс",
        category="Упаковка",
        city="Москва / Санкт-Петербург",
        regions="Москва, СПб, РФ",
        description="Производство гибкой барьерной упаковки для мясной, молочной "
        "и кондитерской продукции. Опт в Москве и Санкт-Петербурге.",
        website="https://edlw.ru/po-proizvoditelyam/edelveys/",
        phone=None,
        email=None,
        source="https://edlw.ru/po-proizvoditelyam/edelveys/",
        min_order="По запросу",
        price="По запросу",
        certificates=None,
        has_certificates=None,
        delivery="Опт по Москве и СПб",
        has_delivery=True,
        is_real=True,
    ),
    dict(
        name="Арикон Групп",
        category="Бакалея и специи",
        city="Москва",
        regions="РФ",
        description="Более 600 наименований: специи, пряности, приправы и бакалея "
        "оптом. Торговая марка «Арикон Профи» разработана для HoReCa.",
        website="https://www.arikon.ru/",
        phone=None,
        email=None,
        source="https://www.arikon.ru/",
        min_order="Опт (по запросу)",
        price="Оптовые цены (по запросу)",
        certificates="Документы на продукцию — по запросу",
        has_certificates=None,
        delivery="Доставка по РФ",
        has_delivery=True,
        is_real=True,
    ),
    dict(
        name="Айдиго (Aidigo)",
        category="Бакалея и специи",
        city="Екатеринбург",
        regions="Вся Россия",
        description="Специи и приправы для HoReCa, ресторанов и кафе. Опт и розница, "
        "доставка по всей стране от 1 дня.",
        website="https://aidigo-shop.ru/catalog/pryanosti_dlya_profi/",
        phone=None,
        email=None,
        source="https://aidigo-shop.ru/catalog/pryanosti_dlya_profi/",
        min_order="По запросу",
        price="По запросу",
        certificates=None,
        has_certificates=None,
        delivery="Доставка по РФ от 1 дня",
        has_delivery=True,
        is_real=True,
    ),
    dict(
        name="Мос-Милк",
        category="Молочная продукция",
        city="Москва",
        regions="Москва и Московская область",
        description="Поставки молочной продукции для HoReCa с 2017 года: молоко, "
        "сливки, сметана, масло, творог, йогурты, соусы и десерты.",
        website="https://mos-milk.ru/catalog/horeca",
        phone=None,
        email=None,
        source="https://mos-milk.ru/catalog/horeca",
        min_order="По запросу",
        price="По запросу",
        certificates=None,
        has_certificates=None,
        delivery="Быстрая доставка по Москве и МО",
        has_delivery=True,
        is_real=True,
    ),
    dict(
        name="Русагропром",
        category="Замороженные продукты",
        city="Москва",
        regions="Вся Россия",
        description="Замороженные ягоды, грибы и овощи оптом. Поставки в торговые "
        "сети и предприятия общепита по всей России.",
        website="https://rusagro-prom.ru/",
        phone=None,
        email=None,
        source="https://rusagro-prom.ru/",
        min_order="Опт (по запросу)",
        price="По запросу",
        certificates=None,
        has_certificates=None,
        delivery="Поставки по РФ",
        has_delivery=True,
        is_real=True,
    ),
    dict(
        name="Лина",
        category="Готовая продукция",
        city="Москва",
        regions="Москва, РФ",
        description="Собственное производство: свыше 150 наименований замороженной "
        "готовой продукции и полуфабрикатов для HoReCa оптом.",
        website="https://lina.bz/horeca/",
        phone=None,
        email=None,
        source="https://lina.bz/horeca/",
        min_order="По запросу",
        price="По запросу",
        certificates="Документы — по запросу",
        has_certificates=None,
        delivery="Поставки для HoReCa",
        has_delivery=True,
        is_real=True,
    ),
    dict(
        name="GFC",
        category="Готовая продукция",
        city="Москва",
        regions="Москва и область, РФ",
        description="Замороженные готовые блюда оптом для кафе и ресторанов — "
        "часть широкого каталога продуктов для HoReCa.",
        website="https://gfc-russia.ru/catalog/gotovye-blyuda-zamorozhennye",
        phone=None,
        email=None,
        source="https://gfc-russia.ru/catalog/gotovye-blyuda-zamorozhennye",
        min_order="По запросу",
        price="По запросу",
        certificates=None,
        has_certificates=None,
        delivery="Доставка и самовывоз по Москве, МО и РФ",
        has_delivery=True,
        is_real=True,
    ),
    dict(
        name="OnlyHoreca",
        category="Напитки",
        city="Москва",
        regions="Москва и Московская область",
        description="Напитки, вода, соки и кола оптом для ресторанов, баров и кафе. "
        "Приём заказов круглосуточно.",
        website="https://horecaonly.ru/",
        phone=None,
        email=None,
        source="https://horecaonly.ru/",
        min_order="По запросу",
        price="По запросу",
        certificates=None,
        has_certificates=None,
        delivery="Бесплатная доставка по Москве и МО",
        has_delivery=True,
        is_real=True,
    ),
    dict(
        name="ОнТап (OnTap)",
        category="Напитки",
        city="Москва",
        regions="Москва, РФ",
        description="Дистрибьютор напитков для HoReCa с 1996 года: вода, соки, "
        "энергетики, пиво и сидр; прямые контракты с производителями.",
        website="https://ontap.ru/",
        phone=None,
        email=None,
        source="https://ontap.ru/",
        min_order="По запросу",
        price="По запросу",
        certificates=None,
        has_certificates=None,
        delivery="Доставка по Москве",
        has_delivery=True,
        is_real=True,
    ),
    dict(
        name="Меридиан",
        category="Мясо и птица",
        city="Москва",
        regions="Москва, СПб, регионы РФ",
        description="Поставщик продуктов для HoReCa с 2005 года; мясо и птица "
        "в ассортименте. Доставка на следующий день после заказа.",
        website="https://horeca.meridian-llc.ru/",
        phone=None,
        email=None,
        source="https://horeca.meridian-llc.ru/",
        min_order="По запросу",
        price="По запросу",
        certificates=None,
        has_certificates=None,
        delivery="Доставка на следующий день, бесплатно от 3 000 ₽",
        has_delivery=True,
        is_real=True,
    ),
    dict(
        name="EvroFresh",
        category="Овощи и фрукты",
        city="Москва",
        regions="Москва и область",
        description="Оптовые поставки овощей и фруктов для HoReCa; бесплатная "
        "доставка со склада в Москве в день заказа.",
        website="https://evrofresh.ru/",
        phone=None,
        email=None,
        source="https://evrofresh.ru/",
        min_order="По запросу",
        price="По запросу",
        certificates=None,
        has_certificates=None,
        delivery="Бесплатная доставка по Москве в день заказа",
        has_delivery=True,
        is_real=True,
    ),
    # --- Рыба и морепродукты ---
    dict(
        name="ПТК Экор-Фиш",
        category="Рыба и морепродукты",
        city="Москва",
        regions="Москва, СПб, Краснодар",
        description="Переработка и оптовые поставки рыбы и морепродуктов для HoReCa — "
        "более 3500 позиций.",
        website="https://ekorfish.com/",
        phone=None, email=None, source="https://ekorfish.com/",
        min_order="По запросу", price="По запросу",
        certificates=None, has_certificates=None,
        delivery="Доставка по Москве, СПб и Краснодару",
        has_delivery=True, is_real=True,
    ),
    dict(
        name="Рыбный Порт",
        category="Рыба и морепродукты",
        city="Москва",
        regions="Москва, РФ",
        description="Переработка и оптово-розничная торговля рыбой и морепродуктами "
        "для HoReCa; на рынке с 1996 года.",
        website="https://fishport.com/",
        phone=None, email=None, source="https://fishport.com/",
        min_order="По запросу", price="По запросу",
        certificates=None, has_certificates=None,
        delivery="Поставки по РФ",
        has_delivery=True, is_real=True,
    ),
    dict(
        name="SeafoodLine",
        category="Рыба и морепродукты",
        city="Москва",
        regions="Москва, РФ",
        description="Импорт замороженной рыбы и морепродуктов для HoReCa с 2007 года; "
        "крупный поставщик в Москве.",
        website="https://seafoodline.ru/",
        phone=None, email=None, source="https://seafoodline.ru/",
        min_order="По запросу", price="По запросу",
        certificates=None, has_certificates=None,
        delivery="Доставка по Москве и РФ",
        has_delivery=True, is_real=True,
    ),
    # --- Хлебобулочные и выпечка ---
    dict(
        name="GF Premium Bakery",
        category="Хлебобулочные и выпечка",
        city="Москва",
        regions="Москва, РФ",
        description="Замороженное тесто и выпечка оптом: хлеб, круассаны, слойки, "
        "тесто для пиццы; для пекарен, кафе и пиццерий.",
        website="https://gf-d.ru/",
        phone=None, email=None, source="https://gf-d.ru/",
        min_order="Крупный и мелкий опт", price="По запросу",
        certificates=None, has_certificates=None,
        delivery="Доставка по Москве и РФ",
        has_delivery=True, is_real=True,
    ),
    dict(
        name="ТД «ЛФБ»",
        category="Хлебобулочные и выпечка",
        city="Москва",
        regions="Москва, СПб, РФ",
        description="С 2009 года поставляет замороженные хлебобулочные и кондитерские "
        "изделия для кафе, ресторанов, пекарен и торговых сетей.",
        website="https://lfb.su/",
        phone=None, email=None, source="https://lfb.su/",
        min_order="Мелкий опт", price="По запросу",
        certificates=None, has_certificates=None,
        delivery="Доставка по Москве и СПб",
        has_delivery=True, is_real=True,
    ),
    dict(
        name="Балтийский хлеб",
        category="Хлебобулочные и выпечка",
        city="Санкт-Петербург",
        regions="СЗФО",
        description="Замороженная выпечка из натуральных ингредиентов для кафе, "
        "ресторанов и магазинов; опт в СПб.",
        website="https://www.baltic-bread.ru/products/zamorozhennaya-vypechka/",
        phone=None, email=None,
        source="https://www.baltic-bread.ru/products/zamorozhennaya-vypechka/",
        min_order="По запросу", price="По запросу",
        certificates=None, has_certificates=None,
        delivery="Опт по СПб",
        has_delivery=True, is_real=True,
    ),
    # --- Ингредиенты (дополнительно) ---
    dict(
        name="АСИЛАБ",
        category="Ингредиенты",
        city="Москва",
        regions="РФ",
        description="Эмульгаторы и стабилизаторы для пищевой промышленности "
        "(преемник российского отделения Palsgaard).",
        website="https://asilab.ru/",
        phone=None, email=None, source="https://asilab.ru/",
        min_order="По запросу", price="По запросу",
        certificates="Документы — по запросу", has_certificates=None,
        delivery="Поставки по РФ",
        has_delivery=True, is_real=True,
    ),
    dict(
        name="ТД «Аргол»",
        category="Ингредиенты",
        city="Москва",
        regions="Москва, СПб, РФ",
        description="Оптовый поставщик пищевых ингредиентов и добавок по РФ; "
        "представительства в Москве и Санкт-Петербурге.",
        website="https://tdargol.ru/",
        phone=None, email=None, source="https://tdargol.ru/",
        min_order="По запросу", price="По запросу",
        certificates="Документы — по запросу", has_certificates=None,
        delivery="Поставки по РФ",
        has_delivery=True, is_real=True,
    ),
    # --- Бакалея и специи (дополнительно) ---
    dict(
        name="Verde Tech",
        category="Бакалея и специи",
        city="Санкт-Петербург",
        regions="СЗФО, РФ",
        description="Специи и пряности оптом для мясопереработки, HoReCa и "
        "консервации; прямые поставки с завода.",
        website="https://verdetech.ru/category/katalog/speczii-i-pryanosti/",
        phone=None, email=None,
        source="https://verdetech.ru/category/katalog/speczii-i-pryanosti/",
        min_order="По запросу", price="По запросу",
        certificates=None, has_certificates=None,
        delivery="Поставки по РФ",
        has_delivery=True, is_real=True,
    ),
    dict(
        name="ТД «Гурман»",
        category="Бакалея и специи",
        city="Москва",
        regions="Москва, РФ",
        description="Более 10 лет поставляет продукты для HoReCa: специи, приправы, "
        "молочную продукцию и др.",
        website="https://gurman-llc.ru/",
        phone=None, email=None, source="https://gurman-llc.ru/",
        min_order="По запросу", price="По запросу",
        certificates=None, has_certificates=None,
        delivery="Доставка по Москве и РФ",
        has_delivery=True, is_real=True,
    ),
    # --- Мультикатегорийные дистрибьюторы HoReCa (одно окно на много категорий) ---
    dict(
        name="Свит Лайф Фудсервис",
        category="Дистрибьютор HoReCa",
        city="Санкт-Петербург",
        regions="СПб и ещё 27 регионов РФ",
        description="Один из крупнейших оптовых поставщиков продуктов для HoReCa — "
        "более 5200 позиций по широкому спектру категорий.",
        website="https://swlife.ru/",
        phone=None, email=None, source="https://swlife.ru/",
        min_order="По запросу", price="По запросу",
        certificates=None, has_certificates=None,
        delivery="Доставка по СПб и 27 регионам РФ",
        has_delivery=True, is_real=True,
    ),
    dict(
        name="EastFood",
        category="Дистрибьютор HoReCa",
        city="Санкт-Петербург",
        regions="СЗФО и далее (1500+ км от РЦ)",
        description="Оптовые поставки для HoReCa: 2000+ позиций от 400 российских и "
        "зарубежных производителей.",
        website="https://eastfood.spb.ru/",
        phone=None, email=None, source="https://eastfood.spb.ru/",
        min_order="По запросу", price="По запросу",
        certificates=None, has_certificates=None,
        delivery="Доставка из РЦ на 1500+ км",
        has_delivery=True, is_real=True,
    ),
    dict(
        name="MARR RUSSIA",
        category="Дистрибьютор HoReCa",
        city="Москва",
        regions="Москва, СПб, Новосибирск, Екатеринбург",
        description="Поставщик продуктов для ресторанов и кафе; присутствие сразу "
        "в нескольких городах России.",
        website="https://marr.ru/",
        phone=None, email=None, source="https://marr.ru/",
        min_order="По запросу", price="По запросу",
        certificates=None, has_certificates=None,
        delivery="Доставка по городам присутствия",
        has_delivery=True, is_real=True,
    ),
    dict(
        name="ОПТ-Торг HoReCa",
        category="Дистрибьютор HoReCa",
        city="Москва",
        regions="Москва, МО, РФ",
        description="Поставщик продуктов оптом для ресторанов, кафе и гостиниц: "
        "бакалея, молочка, мясо, заморозка, специи.",
        website="https://opttorg-horeca.ru/",
        phone=None, email=None, source="https://opttorg-horeca.ru/",
        min_order="По запросу", price="По запросу",
        certificates=None, has_certificates=None,
        delivery="Доставка по Москве и МО за 24 ч, экспресс в день обращения",
        has_delivery=True, is_real=True,
    ),
]

# --- ДЕМО поставщики (синтетика с полными данными для демонстрации скоринга) ---
DEMO = [
    dict(
        name="ВкусБаза",
        category="Бакалея и специи",
        city="Москва",
        regions="ЦФО, доставка по РФ",
        description="Бакалея, специи и приправы оптом для общепита и производства.",
        website="https://vkusbaza.example.ru",
        phone="+7 (495) 100-20-30",
        email="opt@vkusbaza.example.ru",
        min_order="от 20 000 ₽",
        min_order_num=20000,
        price="≈ 180 ₽/кг",
        price_num=180,
        certificates="ГОСТ, декларации соответствия, протоколы лаборатории",
        has_certificates=True,
        delivery="Доставка по Москве 1–2 дня, по РФ — ТК",
        has_delivery=True,
    ),
    dict(
        name="МолокоПлюс",
        category="Молочная продукция",
        city="Санкт-Петербург",
        regions="СЗФО",
        description="Фермерская молочная продукция: молоко, сыры, творог, сливки.",
        website="https://molokoplus.example.ru",
        phone="+7 (812) 200-30-40",
        email="sales@molokoplus.example.ru",
        min_order="от 15 000 ₽",
        min_order_num=15000,
        price="≈ 95 ₽/л",
        price_num=95,
        certificates="Ветеринарные документы, декларации ТР ТС",
        has_certificates=True,
        delivery="Своя логистика по СПб и ЛО, рефрижераторы",
        has_delivery=True,
    ),
    dict(
        name="АгроСвежесть",
        category="Овощи и фрукты",
        city="Краснодар",
        regions="ЮФО, доставка по РФ",
        description="Сезонные овощи и фрукты от фермеров Краснодарского края.",
        website="https://agrosvezhest.example.ru",
        phone="+7 (861) 300-40-50",
        email="zakaz@agrosvezhest.example.ru",
        min_order="от 50 кг",
        min_order_num=8000,
        price="≈ 70 ₽/кг",
        price_num=70,
        certificates="Декларации соответствия",
        has_certificates=True,
        delivery="Самовывоз или доставка по ЮФО",
        has_delivery=True,
    ),
    dict(
        name="МясоОпт",
        category="Мясо и птица",
        city="Ростов-на-Дону",
        regions="ЮФО, ЦФО",
        description="Охлаждённое и замороженное мясо, птица, субпродукты оптом.",
        website="https://myasoopt.example.ru",
        phone="+7 (863) 400-50-60",
        email="opt@myasoopt.example.ru",
        min_order="от 100 кг",
        min_order_num=45000,
        price="≈ 420 ₽/кг",
        price_num=420,
        certificates="Ветсертификаты, ХАССП, Меркурий",
        has_certificates=True,
        delivery="Рефрижераторы, доставка по ЮФО и ЦФО",
        has_delivery=True,
    ),
    dict(
        name="ПакЛайн",
        category="Упаковка",
        city="Новосибирск",
        regions="СФО, доставка по РФ",
        description="Пищевая упаковка, контейнеры, плёнка, пакеты оптом.",
        website="https://pakline.example.ru",
        phone="+7 (383) 500-60-70",
        email="info@pakline.example.ru",
        min_order="от 10 000 ₽",
        min_order_num=10000,
        price="≈ 6 ₽/шт",
        price_num=6,
        certificates="Декларации на пищевой контакт",
        has_certificates=True,
        delivery="Доставка по СФО, по РФ — ТК",
        has_delivery=True,
    ),
    dict(
        name="ФрешФрост",
        category="Замороженные продукты",
        city="Екатеринбург",
        regions="УрФО",
        description="Шоковая заморозка: овощи, ягоды, картофель фри, полуфабрикаты.",
        website="https://freshfrost.example.ru",
        phone="+7 (343) 600-70-80",
        email="sales@freshfrost.example.ru",
        min_order="от 30 000 ₽",
        min_order_num=30000,
        price="≈ 130 ₽/кг",
        price_num=130,
        certificates="ТР ТС, протоколы испытаний",
        has_certificates=True,
        delivery="Свой морозильный терминал, рефротранспорт",
        has_delivery=True,
    ),
    dict(
        name="ИнгредиентПро",
        category="Ингредиенты",
        city="Казань",
        regions="ПФО, доставка по РФ",
        description="Стабилизаторы, эмульгаторы, красители, комплексные добавки.",
        website="https://ingredientpro.example.ru",
        phone="+7 (843) 700-80-90",
        email="opt@ingredientpro.example.ru",
        min_order="от 25 000 ₽",
        min_order_num=25000,
        price="≈ 540 ₽/кг",
        price_num=540,
        certificates="Декларации ТР ТС, спецификации, паспорта качества",
        has_certificates=True,
        delivery="Доставка по ПФО и РФ",
        has_delivery=True,
    ),
    dict(
        name="СпайсМаркет",
        category="Бакалея и специи",
        city="Москва",
        regions="Москва и МО",
        description="Специи и пряности оптом, фасовка под заказ.",
        website="https://spicemarket.example.ru",
        phone="+7 (495) 800-90-10",
        email="info@spicemarket.example.ru",
        min_order="от 30 000 ₽",
        min_order_num=30000,
        price="≈ 210 ₽/кг",
        price_num=210,
        certificates=None,
        has_certificates=False,
        delivery="Доставка по Москве и МО",
        has_delivery=True,
    ),
    dict(
        name="ДейриТрейд",
        category="Молочная продукция",
        city="Москва",
        regions="ЦФО",
        description="Молочная продукция для HoReCa: сыры, масло, сливки.",
        website="https://dairytrade.example.ru",
        phone="+7 (495) 900-10-20",
        email="opt@dairytrade.example.ru",
        min_order="от 25 000 ₽",
        min_order_num=25000,
        price="≈ 110 ₽/л",
        price_num=110,
        certificates="Ветдокументы, декларации ТР ТС",
        has_certificates=True,
        delivery="Доставка по Москве и ЦФО",
        has_delivery=True,
    ),
    dict(
        name="ГотовоФуд",
        category="Готовая продукция",
        city="Санкт-Петербург",
        regions="СЗФО",
        description="Готовые блюда и кулинария глубокой заморозки для общепита.",
        website="https://gotovofood.example.ru",
        phone="+7 (812) 110-20-30",
        email="sales@gotovofood.example.ru",
        min_order="от 40 000 ₽",
        min_order_num=40000,
        price="≈ 320 ₽/кг",
        price_num=320,
        certificates="ХАССП, ТР ТС",
        has_certificates=True,
        delivery="Доставка по СЗФО",
        has_delivery=True,
    ),
    dict(
        name="НапиткиОпт",
        category="Напитки",
        city="Москва",
        regions="ЦФО, доставка по РФ",
        description="Соки, вода, сиропы и безалкогольные напитки оптом.",
        website="https://napitkiopt.example.ru",
        phone="+7 (495) 120-30-40",
        email="opt@napitkiopt.example.ru",
        min_order="от 18 000 ₽",
        min_order_num=18000,
        price="≈ 55 ₽/л",
        price_num=55,
        certificates="Декларации соответствия",
        has_certificates=True,
        delivery="Доставка по Москве и РФ",
        has_delivery=True,
    ),
    dict(
        name="ЭкоУпак",
        category="Упаковка",
        city="Москва",
        regions="ЦФО",
        description="Биоразлагаемая и крафтовая упаковка для еды навынос.",
        website="https://ecoupak.example.ru",
        phone="+7 (495) 130-40-50",
        email="info@ecoupak.example.ru",
        min_order="от 8 000 ₽",
        min_order_num=8000,
        price="≈ 9 ₽/шт",
        price_num=9,
        certificates="Сертификат пищевого контакта, эко-маркировка",
        has_certificates=True,
        delivery="Доставка по Москве 1 день",
        has_delivery=True,
    ),
    dict(
        name="СибПродукт",
        category="Овощи и фрукты",
        city="Новосибирск",
        regions="СФО",
        description="Овощи борщевого набора и фрукты оптом для столовых и кафе.",
        website="https://sibprodukt.example.ru",
        phone="+7 (383) 140-50-60",
        email="zakaz@sibprodukt.example.ru",
        min_order="от 200 кг",
        min_order_num=12000,
        price="≈ 45 ₽/кг",
        price_num=45,
        certificates=None,
        has_certificates=False,
        delivery="Доставка по Новосибирску, самовывоз",
        has_delivery=True,
    ),
    dict(
        name="ПремиумМит",
        category="Мясо и птица",
        city="Москва",
        regions="Москва и МО",
        description="Премиальное мясо, стейки, мраморная говядина для ресторанов.",
        website="https://premiummeat.example.ru",
        phone="+7 (495) 150-60-70",
        email="chef@premiummeat.example.ru",
        min_order="от 60 000 ₽",
        min_order_num=60000,
        price="≈ 1 350 ₽/кг",
        price_num=1350,
        certificates="Ветсертификаты, Меркурий, прослеживаемость",
        has_certificates=True,
        delivery="Доставка по Москве, температурный режим",
        has_delivery=True,
    ),
]


# Редакционные комментарии о поставщиках (раскрывают пункт ТЗ
# «комментарии или заметки по поставщику»). Отделены от личных «Мои заметки».
COMMENTS = {
    # --- реальные ---
    "ГК «Союзоптторг»": "Крупный дистрибьютор с широким ассортиментом под разные отрасли; точные условия уточняются у менеджера.",
    "НЕОС ИНГРЕДИЕНТС": "Своё производство в Подмосковье — плюс к стабильности поставок; на рынке с 1990-х.",
    "RUSFLEX": "Делают печать на упаковке под бренд; тиражи и сроки лучше запрашивать заранее.",
    "Эдельвейс": "Барьерная упаковка под мясную, молочную и кондитерскую продукцию; опт в Москве и СПб.",
    "Арикон Групп": "Отдельная линейка «Профи» под HoReCa — удобно для общепита; ассортимент 600+ позиций.",
    "Айдиго (Aidigo)": "Быстрая доставка по стране от 1 дня; работают и оптом, и в розницу.",
    "Мос-Милк": "Заточены под HoReCa, оперативная доставка; гео-зона узкая — Москва и область.",
    "Русагропром": "Поставляют в федеральные сети — косвенный признак объёмов и стабильности.",
    # --- демо ---
    "ВкусБаза": "Полный пакет документов (ГОСТ, протоколы лаборатории) — удобно проходить проверки.",
    "МолокоПлюс": "Своя логистика с рефрижераторами по СЗФО; фермерское качество.",
    "АгроСвежесть": "Низкая цена и небольшая минималка — хороший вход для малого общепита.",
    "МясоОпт": "ХАССП и «Меркурий» в порядке; учтите высокий минимальный заказ от 100 кг.",
    "ПакЛайн": "Низкий порог входа по сумме заказа; широкий выбор тары.",
    "ФрешФрост": "Свой морозильный терминал — шоковая заморозка без потери качества.",
    "ИнгредиентПро": "Паспорта качества и спецификации на каждую позицию; цена выше средней.",
    "СпайсМаркет": "Документы не подтверждены — уточните перед заказом; фасовка под заказ.",
    "ДейриТрейд": "Стабильный поставщик молочки для HoReCa по ЦФО.",
    "ГотовоФуд": "Готовые блюда глубокой заморозки экономят время на кухне; ХАССП есть.",
    "НапиткиОпт": "Низкие минималка и цена; широкий выбор безалкогольных напитков.",
    "ЭкоУпак": "Биоразлагаемая упаковка с эко-маркировкой — плюс для позиционирования бренда.",
    "СибПродукт": "Документы не подтверждены; зато низкая цена на борщевой набор.",
    "ПремиумМит": "Премиальный сегмент (мраморная говядина) — высокий чек и минимальный заказ.",
    # --- реальные, добавленные по категориям с дефицитом ---
    "Лина": "Своё производство, 150+ позиций заморозки под HoReCa — много позиций у одного поставщика.",
    "GFC": "Широкий каталог под HoReCa (готовые блюда, мясо, овощи) — единое окно; условия уточняются у менеджера.",
    "OnlyHoreca": "Приём заказов круглосуточно и доставка по Москве и МО — удобно при плавающем спросе.",
    "ОнТап (OnTap)": "На рынке с 1996 года, прямые контракты с производителями; есть и пиво/сидр — учтите профиль.",
    "Меридиан": "С 2005 года, доставка на следующий день и бесплатно от 3 000 ₽ — низкий порог входа.",
    "EvroFresh": "Свежие овощи и фрукты с доставкой в день заказа — важно для скоропорта.",
    "ПТК Экор-Фиш": "Своя переработка и 3500+ позиций — закрывает рыбное направление целиком; доставка в три города.",
    "Рыбный Порт": "Опыт с 1996 года и собственная переработка — плюс к стабильности качества.",
    "SeafoodLine": "Импортная заморозка с 2007 года, крупные объёмы — удобно для сетей.",
    "GF Premium Bakery": "Замороженное тесто и выпечка под пекарню/пиццерию — широкий ассортимент полуфабрикатов.",
    "ТД «ЛФБ»": "С 2009 года; работают и с пекарнями, и с сетями — гибко по объёмам.",
    "Балтийский хлеб": "Натуральный состав, опт в СПб — хороший вариант для СЗФО.",
    "АСИЛАБ": "Нишевая экспертиза по эмульгаторам/стабилизаторам (наследие Palsgaard).",
    "ТД «Аргол»": "Представительства в двух столицах — удобно для поставок и в Москву, и в СПб.",
    "Verde Tech": "Прямые поставки специй с акцентом на мясопереработку и HoReCa; база в СПб.",
    "ТД «Гурман»": "10+ лет в HoReCa, несколько категорий — проверенный мультипоставщик.",
    "Свит Лайф Фудсервис": "Одно окно на 5200+ позиций по СПб и 27 регионам — закрыть много категорий разом.",
    "EastFood": "2000+ позиций от 400 производителей, доставка на 1500+ км — сильная логистика.",
    "MARR RUSSIA": "Присутствие в 4 городах — удобно для сетей в разных регионах.",
    "ОПТ-Торг HoReCa": "Мультикатегорийный поставщик с экспресс-доставкой в день обращения по Москве и МО.",
}


def seed():
    """Залить данные, если таблица пуста. Безопасно вызывать при каждом старте."""
    db = SessionLocal()
    try:
        if db.query(Supplier).count() > 0:
            return
        for row in REAL:
            row = {**row, "comment": COMMENTS.get(row["name"], "")}
            db.add(Supplier(**row))
        for row in DEMO:
            row = {**row, "source": "Демо-данные", "is_real": False,
                   "comment": COMMENTS.get(row["name"], "")}
            db.add(Supplier(**row))
        db.commit()
    finally:
        db.close()
